### ISSUE TITLE
Potential EULA violation

### ISSUE THREAD

**Issue by fontpolice** [toadkicker/logo#1]
Dear toadkicker,

It has come to our attention through [FontFinder](http://www.fontfinder.io) that your hosting of gothmlig-webfont.woff in this _public_ repository could be a potential violation of the End User License Agreement (EULA) between yourself and the respective foundry.

We recommend that you [remove](https://github.com/blog/1545-deleting-files-on-github) the files to avoid further action.

Sincerely,
The Font Police

**Comment by toadkicker** [comment]
http://1wdojq181if3tdg01yomaof86.wpengine.netdna-cdn.com/wp-content/uploads/2015/08/8Kxjz.gif
